// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvZqtRlfgwCJ1Y31CXmK7xzLHUBOPmzU',
    appId: '1:207709990528:web:41e3eb8d569ff76a300065',
    messagingSenderId: '207709990528',
    projectId: 'movie-faf1b',
    authDomain: 'movie-faf1b.firebaseapp.com',
    storageBucket: 'movie-faf1b.firebasestorage.app',
    measurementId: 'G-PHNVC603VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGhRwdcrNut_HNcSk_3oSn6Q0jXXNIyc',
    appId: '1:207709990528:android:84edb97238afaa96300065',
    messagingSenderId: '207709990528',
    projectId: 'movie-faf1b',
    storageBucket: 'movie-faf1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9H8Qbs-mtKdW4O64iixXeRoPLNnZKG8k',
    appId: '1:207709990528:ios:10376cc9ea1e2e3e300065',
    messagingSenderId: '207709990528',
    projectId: 'movie-faf1b',
    storageBucket: 'movie-faf1b.firebasestorage.app',
    iosBundleId: 'com.example.moiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9H8Qbs-mtKdW4O64iixXeRoPLNnZKG8k',
    appId: '1:207709990528:ios:10376cc9ea1e2e3e300065',
    messagingSenderId: '207709990528',
    projectId: 'movie-faf1b',
    storageBucket: 'movie-faf1b.firebasestorage.app',
    iosBundleId: 'com.example.moiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsvZqtRlfgwCJ1Y31CXmK7xzLHUBOPmzU',
    appId: '1:207709990528:web:00edfbb63fa5d584300065',
    messagingSenderId: '207709990528',
    projectId: 'movie-faf1b',
    authDomain: 'movie-faf1b.firebaseapp.com',
    storageBucket: 'movie-faf1b.firebasestorage.app',
    measurementId: 'G-9ZM0MVHW75',
  );
}
